name: Conan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cpp:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler:
          - name: gcc 9
            docker: gcc9-ubuntu16.04:1.39.0
            libcxx: libstdc++11
          - name: clang 11
            docker: clang11-ubuntu16.04:1.39.0
            libcxx: libc++
    container:
      image: conanio/${{ matrix.compiler.docker }}
      env:
        CONAN_RUN_TESTS: 1
    steps:
      - name: Fix clone Permissons
        run: |
          sudo chmod -R 777 /__w/gerbera/gerbera
      - uses: actions/checkout@v2
      - name: build and test
        env:
          HOME: /home/conan
        run: |
          ln -s /__w/gerbera/gerbera $HOME/repo
          cd $HOME/repo

          conan profile update settings.compiler.libcxx=${{ matrix.compiler.libcxx }} default

          conan install . \
            --install-folder build \
            --profile conan/dev \
            --build missing
          conan build . --build-folder build
