name: docker

on:
  push:
    branches:
      - master
      - docker-multiarch
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        docker-arch: [ linux/amd64, linux/386, ]#linux/arm64, linux/arm/v7, linux/arm/v6, linux/riscv64 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: gerbera/gerbera
          tag-sha: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - if: "${{ github.repository == 'gerbera/gerbera' && ( startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master' ) }}"
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.docker-arch }}
          push: ${{ github.repository == 'gerbera/gerbera' && ( startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master' ) }}"
#          tags: ${{ steps.docker_meta.outputs.tags }}
#          labels: ${{ steps.docker_meta.outputs.labels }}

      - uses: frabert/replace-string-action@v1.2
        id: replace
        with:
          pattern: '\/'
          string: ${{ matrix.docker-arch }}
          replace-with: '-'

      - name: "Write Digest file"
        run: |
          echo "${{ steps.build.outputs.digest }}"
          echo "${{ steps.build.outputs.digest }}" > ${{ steps.replace.outputs.replaced }}.digest

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.replace.outputs.replaced }}.digest
          path: ${{ steps.replace.outputs.replaced }}.digest

  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello"

      - uses: actions/download-artifact@v2

      - name: Display structure of downloaded files
        run: ls -R
